const fs = require("fs");
const path = require("path");
const { withAndroidStyles, withAppBuildGradle, withDangerousMod } = require("expo/config-plugins");

const MATERIAL = "com.google.android.material:material:1.13.0";

/**
 * Android app theme: Material 3 with the app's colors (it's AppCompat by default).
 *
 * The native parts drawn by Android itself (the Material date/time pickers, Alert dialogs)
 * read their colors from this theme, so it gets the same roles the JS UI uses:
 * - Android 12+: Material You, i.e. the user's wallpaper colors (values-v31).
 * - Older phones: the Material 3 scheme generated from the brand blue (values).
 * Each has a night variant, so dark mode matches too. Keep in step with src/ui/theme.ts.
 *
 * The Material library already ships inside react-native-screens and expo-router; it's
 * declared on the app too so the theme always resolves. Keep the version in step with them.
 */

// Theme attribute -> color resource name.
const ROLES = {
  colorPrimary: "app_m3_primary",
  colorOnPrimary: "app_m3_on_primary",
  colorPrimaryContainer: "app_m3_primary_container",
  colorOnPrimaryContainer: "app_m3_on_primary_container",
  colorSecondaryContainer: "app_m3_secondary_container",
  colorOnSecondaryContainer: "app_m3_on_secondary_container",
  colorSurface: "app_m3_surface",
  colorSurfaceContainerHigh: "app_m3_surface_container_high",
  colorOnSurface: "app_m3_on_surface",
  colorOnSurfaceVariant: "app_m3_on_surface_variant",
  colorOutline: "app_m3_outline",
  "android:colorBackground": "app_m3_surface",
};

// values / values-night: fixed scheme from the brand blue.
const brand = {
  light: {
    app_m3_primary: "#005AC1",
    app_m3_on_primary: "#FFFFFF",
    app_m3_primary_container: "#D8E2FF",
    app_m3_on_primary_container: "#001A41",
    app_m3_secondary_container: "#DBE2F9",
    app_m3_on_secondary_container: "#141B2C",
    app_m3_surface: "#F9F9FF",
    app_m3_surface_container_high: "#E7E8EE",
    app_m3_on_surface: "#1A1B20",
    app_m3_on_surface_variant: "#44474F",
    app_m3_outline: "#74777F",
  },
  dark: {
    app_m3_primary: "#ADC6FF",
    app_m3_on_primary: "#002E69",
    app_m3_primary_container: "#004494",
    app_m3_on_primary_container: "#D8E2FF",
    app_m3_secondary_container: "#3E4759",
    app_m3_on_secondary_container: "#DBE2F9",
    app_m3_surface: "#111318",
    app_m3_surface_container_high: "#282A2F",
    app_m3_on_surface: "#E2E2E9",
    app_m3_on_surface_variant: "#C4C6D0",
    app_m3_outline: "#8E9099",
  },
};

// values-v31 / values-night-v31: the system's wallpaper-based tonal palettes.
const sys = (name) => `@android:color/system_${name}`;
const dynamic = {
  light: {
    app_m3_primary: sys("accent1_600"),
    app_m3_on_primary: sys("accent1_0"),
    app_m3_primary_container: sys("accent1_100"),
    app_m3_on_primary_container: sys("accent1_900"),
    app_m3_secondary_container: sys("accent2_100"),
    app_m3_on_secondary_container: sys("accent2_900"),
    app_m3_surface: sys("neutral1_10"),
    app_m3_surface_container_high: sys("neutral1_100"),
    app_m3_on_surface: sys("neutral1_900"),
    app_m3_on_surface_variant: sys("neutral2_700"),
    app_m3_outline: sys("neutral2_500"),
  },
  dark: {
    app_m3_primary: sys("accent1_200"),
    app_m3_on_primary: sys("accent1_800"),
    app_m3_primary_container: sys("accent1_700"),
    app_m3_on_primary_container: sys("accent1_100"),
    app_m3_secondary_container: sys("accent2_700"),
    app_m3_on_secondary_container: sys("accent2_100"),
    app_m3_surface: sys("neutral1_900"),
    app_m3_surface_container_high: sys("neutral1_800"),
    app_m3_on_surface: sys("neutral1_100"),
    app_m3_on_surface_variant: sys("neutral2_200"),
    app_m3_outline: sys("neutral2_400"),
  },
};

function colorsXml(values) {
  const lines = Object.entries(values).map(([name, value]) => `  <color name="${name}">${value}</color>`);
  return `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by plugins/withMaterial3Theme.js -->\n<resources>\n${lines.join("\n")}\n</resources>\n`;
}

function withThemeColors(config) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const res = path.join(cfg.modRequest.platformProjectRoot, "app/src/main/res");
      const files = {
        values: brand.light,
        "values-night": brand.dark,
        "values-v31": dynamic.light,
        "values-night-v31": dynamic.dark,
      };
      for (const [dir, values] of Object.entries(files)) {
        fs.mkdirSync(path.join(res, dir), { recursive: true });
        fs.writeFileSync(path.join(res, dir, "app_m3_colors.xml"), colorsXml(values));
      }
      return cfg;
    },
  ]);
}

module.exports = function withMaterial3Theme(config) {
  config = withAndroidStyles(config, (cfg) => {
    const styles = cfg.modResults.resources.style ?? [];
    const appTheme = styles.find((s) => s.$.name === "AppTheme");
    if (appTheme) {
      appTheme.$.parent = "Theme.Material3.DayNight.NoActionBar";
      const items = (appTheme.item ??= []);
      for (const [attr, color] of Object.entries(ROLES)) {
        const existing = items.find((i) => i.$.name === attr);
        if (existing) existing._ = `@color/${color}`;
        else items.push({ $: { name: attr }, _: `@color/${color}` });
      }
    }
    return cfg;
  });
  config = withThemeColors(config);
  return withAppBuildGradle(config, (cfg) => {
    if (!cfg.modResults.contents.includes(MATERIAL)) {
      cfg.modResults.contents = cfg.modResults.contents.replace(
        /dependencies\s*\{/,
        (match) => `${match}\n    implementation("${MATERIAL}")`,
      );
    }
    return cfg;
  });
};
